apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wiki-app-tai333-ingress
  namespace: dev-tai333-k8s
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - dev-k8s.tai333.cloud
      secretName: dev-k8s-tai333-tls
  rules:
    - host: dev-k8s.tai333.cloud
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wiki-app
                port:
                  number: 80
